permalink:   pretty
highlighter: pygments
markdown:    rdiscount
rdiscount:
  extensions: [smart]
name: Josh Summers
description: 'A blog about learning while making things with good people. '
url: http://joshsummers.co.uk
auto: true
feedburner_id: joshsummers
future: true
gems: 
  - jekyll-redirect-from
